name: First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "Hello World"

        - name: List files
          run: ls -lah

        - name: Read file
          run: cat README.md