name: First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List & read file
          run: | 
            echo "Github Action"
            ls -lah
            cat README.md

        - name: Generate ASCII artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWRR " >> dragon.txt


        # - name: List files
        #   run: ls -lah

        # - name: Read file
        #   run: cat README.md