name: Generate ASCII WorkArt

on: 
  push

jobs:
    build_job1:
      runs-on: ubuntu-latest
      steps:

      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y

      - name: Executing cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWRR " >> dragon.txt

      - name: Sleep for 30s
        run: sleep 30

    test_job2:
      needs: build_job1
      runs-on: ubuntu-latest
      steps:
      - name: Sleep for 10s
        run: sleep 10

      - name: Test file exist
        run: grep -i "dragon" dragon.txt


    deploy_job3:
      needs: test_job2
      runs-on: ubuntu-latest
      steps:
      - name: Read file
        run: cat dragon.txt

      - name: List repo file
        run: ls -ltra