name: Generate ASCII WorkArt

on: 
  push

jobs:
    build_job1:
      runs-on: ubuntu-latest
      steps:

      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y

      - name: Executing cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWRR " >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

    test_job2:
      needs: build_job1
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Sleep for 10s
        run: sleep 5

      - name: Test file exist
        run: grep -i "dragon" dragon.txt


    deploy_job3:
      needs: test_job2
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Read file
        run: cat dragon.txt

      - name: Deployin
        run: echo "Deploying job...."